### ISSUE TITLE
It's impossible to know how it works

### ISSUE THREAD

**Issue by consecutiotemporum** [KohakuBlueleaf/a1111-sd-webui-locon#14]
I installed Additional Network and have the tab in A1111
Do I need to select LyCORIS here as well?

![Screenshot 2023-03-25 222943](https://user-images.githubusercontent.com/114416380/227743200-4c992b63-46c1-48f3-8924-375bc017f732.png)

I have it selectable in Model 1 of txt2img

![Screenshot 2023-03-25 223011](https://user-images.githubusercontent.com/114416380/227743206-16cce4b2-fbae-4ee2-974f-6fcadb134f8a.png)
### 
**But how do I enter it in the prompt?**

In the usual list of lora it does not exist.

Thx

**Comment by KohakuBlueleaf** [comment]
For now, I removed the support for addnet ext
You should use lycoris model in built-in lora
