### ISSUE TITLE
Can't use lora

### ISSUE THREAD

**Issue by killporter** [KohakuBlueleaf/a1111-sd-webui-locon#16]
i tried installing time and time again the ui from zero, but i continue to get this error at startup:

Error loading script: lora_script.py Traceback (most recent call last): File "/content/gdrive/MyDrive/sd/stable-diffusion-webui/modules/scripts.py", line 256, in load_scripts script_module = script_loading.load_module(scriptfile.path) File "/content/gdrive/MyDrive/sd/stable-diffusion-webui/modules/script_loading.py", line 11, in load_module module_spec.loader.exec_module(module) File "<frozen importlib._bootstrap_external>", line 850, in exec_module File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed File "/content/gdrive/MyDrive/sd/stable-diffusion-webui/extensions-builtin/Lora/scripts/lora_script.py", line 4, in <module> import lora File "/content/gdrive/MyDrive/sd/stable-diffusion-webui/extensions-builtin/Lora/lora.py", line 238, in <module>

Def lora_apply_weights(self: torch.nn.Conv2d | torch.nn.Linear | torch.nn.MultiheadAttention): TypeError: unsupported operand type(s) for |: 'type' and 'type'

Can someone please help?

**Comment by KohakuBlueleaf** [comment]
First,
this is caused by a1111's update
and I have update my extension for it
(will not fix this problem, if you want to avoid this, just use python3.10 or higher)
