### ISSUE TITLE
Unsure if LoCon models are loading correctly.

### ISSUE THREAD

**Issue by weebsplat** [KohakuBlueleaf/a1111-sd-webui-locon#17]
The command window shows `create LoRa` and `enable LoRa` rather than the `create LoCon` and `enable LoCon` shown in the example code on the repo README when using models with the addnet extension and the resulting generated images are low quality compared to how the model should appear.
```
LoRA weight_unet: 0.85, weight_tenc: 0.85, model: swordArtOnlineKirigaya_v30(8a69b051f4e3)0/20 [00:05<00:00,  3.46it/s]
dimension: {128}, alpha: {64.0}, multiplier_unet: 0.85, multiplier_tenc: 0.85
create LoRA for Text Encoder: 72 modules.
create LoRA for U-Net: 278 modules.
original forward/weights is backed up.
enable LoRA for text encoder
enable LoRA for U-Net
shapes for 0 weights are converted.
LoRA model swordArtOnlineKirigaya_v30(8a69b051f4e3) loaded: <All keys matched successfully>
setting (or sd model) changed. new networks created.
```

**Comment by weebsplat** [comment]
For reference, here's the model used in the example, though this seems to apply to every LoCon model I've tried. Perhaps I'm just being stupid, but I'd like to verify if that's the case or not.

https://civitai.com/models/21280/sword-art-online-kirigaya-suguha-locon-lora

**Comment by KohakuBlueleaf** [comment]
this extension doesn't support addnet
and since a1111 already support lora for sdv2 and my extension also hook on it
I have no plan to support kohya's addnet

**Comment by weebsplat** [comment]
Thanks for clarifying, though it's worth noting that support for addnet is still shown to be a feature in the Readme. Not sure if that needs updating or not.
