### ISSUE TITLE
Do I need this?

### ISSUE THREAD

**Issue by TernaryM01** [KohakuBlueleaf/a1111-sd-webui-locon#7]
I'm a bit confused when reading the README... If my WebUI already has the built-in LORA extension, do I still need this extension to take full advantage of LoCon models? (As I understand, the "Additional Networks" extension was created when WebUI couldn't natively use Hypernetworks and LORAs, but now it's kinda obsolete...)

**Comment by KohakuBlueleaf** [comment]
Yes
You need this extension to load locon/loha model in the "built-in lora"

**Comment by TernaryM01** [comment]
Oh, I get it. So, this extension gives additional machinery behind the scenes, without showing any additional options in the GUI, right? So, I can take full advantage of it without installing the "Additional Networks" extension, right?

**Comment by KohakuBlueleaf** [comment]
@TernaryM01 yes
